version: "3"

services:
  rails:
    build: 
      context: .
      dockerfile: ./docker/local/rails/Dockerfile
    image: organizer_app:0.1.0
    ports:
     - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mailcacher
      - mongodb
      - web-browser
    environment:
      HUB_URL: http://web-browser:4444/wd/hub

  mongodb:
    image : mongo:4.2.7
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongo_organizer:/data/db

  mailcacher:
    build: 
      context: .
      dockerfile: ./docker/local/rails/Dockerfile
    command:
      - mailcatcher
      - --http-ip
      - 0.0.0.0
    image: organizer_app:0.1.0
    ports:
     - 1025:1025
     - 1080:1080
    volumes:
      - .:/app

  web-browser:
    image: selenium/standalone-chrome:3.141.59-zirconium
    command:
      - /opt/bin/entry_point.sh
      - --verbose
    volumes:
      - browser_data:/dev/shm

volumes:
  mongo_organizer:
  browser_data:
