version: "3"

services:
  rails:
    build: 
      context: .
      dockerfile: ./docker/local/rails/Dockerfile
    image: organizer_app:0.1.0
    ports:
     - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mailcacher
      - mongodb

  mongodb:
    image : mongo:4.2.7
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongo_organizer:/data/db

  mailcacher:
    build: 
      context: .
      dockerfile: ./docker/local/rails/Dockerfile
    command:
      - mailcatcher
      - --http-ip
      - 0.0.0.0
    image: organizer_app:0.1.0
    ports:
     - 1025:1025
     - 1080:1080
    volumes:
      - .:/app

volumes:
  mongo_organizer:
